@baseURL=http://localhost:3000
@host=http://localhost:3000


### Signin
POST {{baseURL}}/signin
Content-Type: application/json

{
  "email": "test1@mail.com",
  "password": "123"
}

### Login
POST {{baseURL}}/login
Content-Type: application/json

{
  "email": "test1@mail.com",
  "password": "123"
}

### Signout
GET {{baseURL}}/signout
Authorization: 'token'