### Signin
POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "test1@mail.com",
  "password": "123"
}


### Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "test1@mail.com",
  "password": "123"
}


### Signout
GET http://localhost:3000/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MmMwZjg4YWVjM2NmOWUyYmE4ODQ2NiIsImVtYWlsIjoidGVzdDFAbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRnTm9OOFRZWms0Z3hjcWM5eDZmZlR1NWhHeFUzVFgvTFN2ZHFXSWlIOTJqMWQveWlmSlF0SyIsIl9fdiI6MH0sImlhdCI6MTY4MDYwOTMxNiwiZXhwIjoxNjgwNjEyOTE2fQ.dBipJYlz-L5-tkfsACJ0hkeS_GtQwHO1WbCCKOUSm7A



### Add one article
POST http://localhost:3000/article
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MmMwZjg4YWVjM2NmOWUyYmE4ODQ2NiIsImVtYWlsIjoidGVzdDFAbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRnTm9OOFRZWms0Z3hjcWM5eDZmZlR1NWhHeFUzVFgvTFN2ZHFXSWlIOTJqMWQveWlmSlF0SyIsIl9fdiI6MH0sImlhdCI6MTY4MDYwOTM5MCwiZXhwIjoxNjgwNjEyOTkwfQ.W-Jf4f3bL3W8ChVlQM5PFjEzkSzNkv93MJUvu-6s-UE

{
  "title": "le meilleur article",
  "content": "best article",
  "category": "sport"
}


### Get all articles
GET http://localhost:3000/article
Content-Type: application/json


### Update article
PUT http://localhost:3000/article/642c10c037706bc2ea2c0769
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MmMwZjg4YWVjM2NmOWUyYmE4ODQ2NiIsImVtYWlsIjoidGVzdDFAbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRnTm9OOFRZWms0Z3hjcWM5eDZmZlR1NWhHeFUzVFgvTFN2ZHFXSWlIOTJqMWQveWlmSlF0SyIsIl9fdiI6MH0sImlhdCI6MTY4MDYwOTMxNiwiZXhwIjoxNjgwNjEyOTE2fQ.dBipJYlz-L5-tkfsACJ0hkeS_GtQwHO1WbCCKOUSm7A

{
  "title": "le meilleur article modified",
  "content": "best article modified",
  "category": "sport"
}


### Delete article
DELETE http://localhost:3000/article/642c10c037706bc2ea2c0769
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MmMwZjg4YWVjM2NmOWUyYmE4ODQ2NiIsImVtYWlsIjoidGVzdDFAbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRnTm9OOFRZWms0Z3hjcWM5eDZmZlR1NWhHeFUzVFgvTFN2ZHFXSWlIOTJqMWQveWlmSlF0SyIsIl9fdiI6MH0sImlhdCI6MTY4MDYwOTMxNiwiZXhwIjoxNjgwNjEyOTE2fQ.dBipJYlz-L5-tkfsACJ0hkeS_GtQwHO1WbCCKOUSm7A


### Get article by category
GET http://localhost:3000/article/sport
Content-Type: application/json


### Search article
GET http://localhost:3000/search/article?query=article
Content-Type: application/json



### Post comment
POST http://localhost:3000/comment/6410895f7e5a41aca6b84183
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MmMwZjg4YWVjM2NmOWUyYmE4ODQ2NiIsImVtYWlsIjoidGVzdDFAbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRnTm9OOFRZWms0Z3hjcWM5eDZmZlR1NWhHeFUzVFgvTFN2ZHFXSWlIOTJqMWQveWlmSlF0SyIsIl9fdiI6MH0sImlhdCI6MTY4MDYwOTMxNiwiZXhwIjoxNjgwNjEyOTE2fQ.dBipJYlz-L5-tkfsACJ0hkeS_GtQwHO1WbCCKOUSm7A

{
  "content": "best comment"
}


### Get my comments
GET http://localhost:3000/comment/me
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MmMwZjg4YWVjM2NmOWUyYmE4ODQ2NiIsImVtYWlsIjoidGVzdDFAbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRnTm9OOFRZWms0Z3hjcWM5eDZmZlR1NWhHeFUzVFgvTFN2ZHFXSWlIOTJqMWQveWlmSlF0SyIsIl9fdiI6MH0sImlhdCI6MTY4MDYwOTMxNiwiZXhwIjoxNjgwNjEyOTE2fQ.dBipJYlz-L5-tkfsACJ0hkeS_GtQwHO1WbCCKOUSm7A


### Edit one comment
PUT http://localhost:3000/comment/edit/642c111f37706bc2ea2c077e
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MmMwZjg4YWVjM2NmOWUyYmE4ODQ2NiIsImVtYWlsIjoidGVzdDFAbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRnTm9OOFRZWms0Z3hjcWM5eDZmZlR1NWhHeFUzVFgvTFN2ZHFXSWlIOTJqMWQveWlmSlF0SyIsIl9fdiI6MH0sImlhdCI6MTY4MDYwOTMxNiwiZXhwIjoxNjgwNjEyOTE2fQ.dBipJYlz-L5-tkfsACJ0hkeS_GtQwHO1WbCCKOUSm7A

{
  "content": "best comment modified"
}

### Delete comment
DELETE http://localhost:3000/comment/delete/642c111f37706bc2ea2c077e
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MmMwZjg4YWVjM2NmOWUyYmE4ODQ2NiIsImVtYWlsIjoidGVzdDFAbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRnTm9OOFRZWms0Z3hjcWM5eDZmZlR1NWhHeFUzVFgvTFN2ZHFXSWlIOTJqMWQveWlmSlF0SyIsIl9fdiI6MH0sImlhdCI6MTY4MDYwOTMxNiwiZXhwIjoxNjgwNjEyOTE2fQ.dBipJYlz-L5-tkfsACJ0hkeS_GtQwHO1WbCCKOUSm7A
